name: SAST

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  verificar-codigo:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: get-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: get-bandit
        run: pip install bandit

      - name: sast
        run: bandit -r workflow